language: go

go:
  - 1.11.x

services:
  - docker

script:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: rNlJ7nwv61k7Ww1Oy4vJImsvEdw4ibmTa0gQ+gCm1zmv64qTw1a+FzkI5B8JgcHutFOpPItQKv8/n+nrJx1MgxG7llDzXZCMettqdnCLnEHY4KGhTVq+HCpY/BxVp/iwYdjzA31UP9WsRIecyB+rXkPVDSwY3NXzrfjmlxz6MoBFg4aGLmaqj3DFC4mCD6HnFcuf+sx7kSWaR0R4jccpIkEmIQ1oKdJeQH7ycC4aqg8rf3FN9QqhjVv62pAPSfGAHoVe826LUPdbFTznJKNmXvrzJYYADpYxrR35H45x6YJLdSisHs3CrDZe08oGO1HuPWnCGxuz/i64nMjE4UO6GA7v8zUiNyw30OBIpyLm7B41nQLE6K9nGGCAftHqhu1SHziVePdIplySGiarIRnBFwJ1RubrBEW5bWCW8CFPnUn/xvFA7kyKrTFJAMgkPA2PR9nomgkY4r7R93QDHaTlKiGYV/2UnD+E2S7OwT70RLswc/AE+WNs3tqVc04RIj10v5f/mSFi8OAGLCKzOoTl2W0dY4Qrbs3wDHtd2MGBPFFzTsnWlF7es7dPua+obHmvnUF0Psdsw+qfuOCnPrMqyAY81uj+Kwj3BrBAMfJUVG/IOBy+THhB5emSZUA2ub92ILa/wBLpHXzqNwRLfzo+aAtjrbUP0vTOlEqRyUtEGik=
  file: "out/"
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    #tags: true
