language: go

go:
  - 1.11.x

services:
  - docker

script:
  - make dist

deploy:
  provider: releases
  api_key:
    secure: XMUHtHgitTnokr/qRhyUr3ZnC+cXIjQSeiL6UqaSVnp/a7YOF1GayuKKtc8mXJ7besYFBEad7wxkUL8dyL2Y7CgsPaLPhmHZOWTG0j9tMfNoZSOumHShrU+KpgEObh0Z7KZtI53mHrGqK2eCcIple001RD9SFyBfaiDAnsJfljlzSIzkDc+DIWC0N90igYfFJB9MZREtjHtR2fiyqy5KGJKpkv8MQQPOauHuFgyH9bW4OhepY8DB3T2OTda95NhvAygk69JZ66bU0J/p8R1Ua6YWE3PXGcazA4aBAHwEGCeS4K0uHt1axOa7WrGsiK03cUre746OjYC7iZsURucw9nx2ewoi9ijOIiDcPc7ZPZypLDLEFzP+NoLM7V9zKITwOeATeXLbwzg89BgK9xWNOhe1ejS04Q/XsALbzWTkWKgVboWnOOGZAPCsE4dS1COkllf4W9hQrR+y1hQX2AKV7JsgCqnRUtpKxojl4d9nlH9BdVE7FXiZGK+0qxOW0TyUZ5kBG1ebbEGNRGq1JmgC9A4hJlMF565rHk7EmVcWKj/SQNvh5uYvPDnkKWm2pG8P/NZVvDY9VLUJsb/hpeUYpaS5boRSAwRQfvuNzDuSBLkZCzWKParSsyC4meOscpqieSMOKtfRFg5AOtmI/bd1aP2dfW3ft72IwLrfb1cRJ6o=
  file: "out/"
  skip_cleanup: true
  draft: true
  on:
    all_branches: true
    #tags: true
